# This is a basic workflow that is manually triggered

name: Compress the preset

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compress"
  compress:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    
    - name: Compress the preset
      run: zip -rv "./zip/franchises_in_Korea.zip" ./src/*
      shell: bash
  
    - name: Commit and Push
      run: |
        git add ./zip
        git config --local user.email "depth221@gmail.com"
        git config --local user.name "Dongha Hwang"
        git commit -m "Compress the preset"
        git push
